opening_title: Postman Visualizer
opening_image: images/consumers.png

closing_title: What Can You Visualize?
closing_image: images/integrations_postmanaut_4.png

markdown: kramdown
highlighter: rouge
relative_permalinks: false
permalink: /news/:year/:month/:day/:title/
excerpt_separator: ""
